showConsole: true
layout:
  scope: section
theme:
  colors:
    text: 
      primary: '#333333'
  typography: 
    headings:
      fontFamily: 'Roboto'
    fontFamily: 'Roboto, Verdana, Geneva, sans-serif'
    fontSize: '14px'
    code:
      fontFamily: '"Courier New",monospace'
      tokens:
        'token.property': 
          color: "#aofbaa"
        string: 
          color: "#aofbaa"
    rightPanelHeading:
      color: white
  rightPanel:
    backgroundColor: "#263238"
  links:
    color: "#6CC496"

redocURL: https://redocpro-cdn.redoc.ly/v1.0.0-beta.13/redocpro-standalone.min.js
redocExport: RedocPro
unstable_externalDescription: description.md
